In [40]:
import numpy as np

liste = [1, 2, 3]
liste_2 = [[1, 2, 3], [4, 5, 6]]
tableau_2 = np.array(liste_2)
print(tableau_2)

tableau = np.array(liste)
print(tableau)
print(type(tableau))

print(tableau == 1)
print(tableau == 2)
print(tableau == 3)

nuplet = (1, 2, 3)

tableau_3 = np.array(nuplet)
print(tableau.shape)
print(tableau_2.shape)
print(tableau_3.shape)
print(tableau_3)

[[1 2 3]
 [4 5 6]]
[1 2 3]
<class 'numpy.ndarray'>
[ True False False]
[False  True False]
[False False  True]
(3,)
(2, 3)
(3,)
[1 2 3]
